Update hardened_malloc.spec based on rpm config changes
rusty-snake/fedora-extras pull request #3
Opened 2024-03-25 05:21 UTC by qoijjj

Why this is needed: https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/f40/f/buildflags.md#switching-to-legacy-relative-relocations

2024-03-25 07:23 UTC, rusty-snake requested changes
Can you increase the release number.

Out of interest, Does it fail at build or runtime?

2024-03-25 16:08 UTC, qoijjj commented
> Can you increase the release number.
> 
> Out of interest, Does it fail at build or runtime?

Increased the release number.

It fails at runtime with:

```
/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /var/run/host/usr/lib64/libhardened_malloc.so)
```

2024-03-25 16:36 UTC, rusty-snake commented
Hmm, somehow it works w/o this for me in a `fedora:40` podman container. Do you get this with all programs?

2024-03-25 16:39 UTC, qoijjj commented
> Hmm, somehow it works w/o this for me in a `fedora:40` podman container. Do you get this with all programs?

No, I should have clarified: only a handful of programs. For example https://flathub.org/apps/com.github.zocker_160.SyncThingy

2024-03-25 17:03 UTC, rusty-snake commented
Compiled and installed syncthing in my podman container. If I run it with `QT_QPA_PLATFORM=offscreen LD_PRELOAD=/usr/lib64/libhardened_malloc.so /usr/local/bin/SyncThingy` I get errors about missing dbus (expected). Which means the `ld.so` is done. Do you know other programs?

Also, since you linked to a flatpak, how do you installed SyncThingy / run it?

2024-03-25 17:29 UTC, RoyalOughtness commented
> Compiled and installed syncthing in my podman container. If I run it with `QT_QPA_PLATFORM=offscreen LD_PRELOAD=/usr/lib64/libhardened_malloc.so /usr/local/bin/SyncThingy` I get errors about missing dbus (expected). Which means the `ld.so` is done. Do you know other programs?
> 
> Also, since you linked to a flatpak, how do you installed SyncThingy / run it?

The flatpak includes syncthing. To repro:

1. Install the flatpak
2. Set the hardened_malloc override: 

`flatpak override --user --filesystem=host-os:ro --env=LD_PRELOAD=/var/run/host/usr/lib64/libhardened_malloc.so`

3. Launch the syncthingy flatpak
4. Observe the error that occurs:

```
/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /var/run/host/usr/lib64/libhardened_malloc.so)
```

2024-03-25 17:31 UTC, qoijjj commented
With hardened_malloc compiled with the change in this PR, the error no longer occurs

2024-03-25 17:33 UTC, rusty-snake commented
Can you reproduce this with an non-flatpak?

https://github.com/flatpak/flatpak/issues/5617#issuecomment-1840662405
> Any native code that exists on the host system OS distribution can legitimately have dependencies on libraries in the host system OS distribution that [...] are too old or incompatible, inside the Flatpak runtime.

2024-03-25 17:35 UTC, qoijjj commented
So far I haven't

2024-07-08 21:16 UTC, closed without merging

2024-07-08 21:16 UTC, rusty-snake commented
Closing then, thanks anyway.